### ISSUE TITLE
corgidrp.data.KGain does not read in an input_dataset for archiving the filenames used to produce the calibration file

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#109]
The class could then include the call to `_record_parent_filenames()`.

**Comment by kjl0025** [comment]
@JuergenSchreiber , just wanted to document this here before I forgot.  Please correct me if I'm misunderstanding something about the implementation.

**Comment by JuergenSchreiber** [comment]
I did not add this since we only had one "pre-defined" value. But I can add it.

**Comment by JuergenSchreiber** [comment]
@semaphoreP merged this into main, so it can be closed
