### ISSUE TITLE
Port L1 -> L2a data analysis code from JPL II&T 

### ISSUE THREAD

**Issue by maxwellmb** [roman-corgi/corgidrp#12]
Many folks at JPL have already done a lot of work on this. Let's not double efforts. 

We will wait for JPL to approve open-sourcing this before really getting to it. 

Included capabilities functions are: 

**L1_to_L2a:**
This will implement the following steps:
         - Separate image from prescan
         - Compute bias from prescan, including offset subtraction, and
           subtract from image
         - Build per-frame cosmic ray masks and remove cosmic rays
         - Correct for nonlinearity

**Comment by semaphoreP** [comment]
Should crop down to 1024/1024 at the end of this process

**Comment by mygouf** [comment]
Should I go ahead and get started on this?

**Comment by semaphoreP** [comment]
I think @m-samland also had some interest in helping with this. @mygouf perhaps you can divide up some of the work to @m-samland so he can help you with this? You could decide to share a branch where you push code for this.

**Comment by mygouf** [comment]
Ok, let me start working on it and think about how to divide and conquer. Once we have a good plan for L1 to L2a we can use a similar template for higher levels port and implementation. We can chat more in person next week.

**Comment by maxwellmb** [comment]
a natural way to divide and conquer might be to break up all the functions in the ttr5_analog.py into separate issues. What do you think?

**Comment by mygouf** [comment]
Yes this is what I had in mind. But wanted to wait for your review before going ahead and starting creating new issues.

**Comment by mygouf** [comment]
> a natural way to divide and conquer might be to break up all the functions in the ttr5_analog.py into separate issues. What do you think?

Yes this is what I had in mind. But wanted to wait for your review before going ahead and starting creating new issues.

**Comment by m-samland** [comment]
Yes, I am interested in helping out with porting these to the new pipeline to get used to the code base. It would be good to discuss with @mygouf so that we can coordinate!

**Comment by maxwellmb** [comment]
Closing this issue since we have split it up into sub-issues.
