### ISSUE TITLE
move specification of good columns used for bias estimation from detector.py to DetectorParams?

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#127]
Perhaps it makes more sense to house the specification of the reliable columns in DetectorParams for flexibility instead of hard-coded in detector.py (if not all the geometry info in detector.py)?

**Comment by semaphoreP** [comment]
Max and I decided for now that we are keeping them in detector.py for now, as we aren't expecting them to change ("constants"). Please re-open if you think there are any issues with this.
