### ISSUE TITLE
.corgidrp directory for config made in __init__.py must be deleted in order for an updated directory to be made

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#128]
Perhaps we should add to the README that a user should delete .corgidrp if a new config is desired upon installation.  Or we could have something in __init__.py to see if necessary keys are present and if not to remake the config?

**Comment by kjl0025** [comment]
Sorry I'm just getting to this.  I deleted my .corgidrp to get __init__.py to install a fresh config, so I don't recall the specific error.  But the error was caused by the addition of a key to the config,  and __init__.py didn't make a new config b/c it currently only does that if one doesn't already exist.   I could fix this in another PR soon if you'd like.

**Comment by semaphoreP** [comment]
Sure, although I'd put this at low priority until we start releasing the code for public consumption.

**Comment by semaphoreP** [comment]
Remaining task: add to README that deleting the .corgidrp directory is a possible troubleshooting solution
