### ISSUE TITLE
Do we want to save read noise?

### ISSUE THREAD

**Issue by semaphoreP** [roman-corgi/corgidrp#135]
**Is your feature request related to a problem? Please describe.**
We calculate the read noise during the Kgain calculation. Do we need it anywhere? 

**Describe the solution you'd like**
If we do, we can save it to the Kgain calibration file.

**Comment by maxwellmb** [comment]
Yes, I don't see why we wouldn't stick it in the header. 
Technically it should also be the first entry in the PTC, I think, but I do like the idea of having it in the header.

**Comment by hsergi** [comment]
calibrate_kgain stores read nosie and its err in the keywords RN and RN_ERR, respectively. See https://github.com/roman-corgi/corgidrp/pull/116

Also, a request for these two new keywords has been added: https://collaboration.ipac.caltech.edu/display/romancoronagraph/EXCAM+headers+wishlist
