### ISSUE TITLE
detect_cosmic_rays draws k gain from DetectorParams instead of KGain class

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#203]
**Is your feature request related to a problem? Please describe.**
Currently, `detect_cosmic_rays` draws the k gain value from `DetectorParams`, but k gain is a calibrated value coming from the corgidrp.data.KGain class.  

**Describe the solution you'd like**
Change the function to draw k gain from corgidrp.data.KGain instead, and adjust tests accordingly.

**Additional context**

**Comment by JuergenSchreiber** [comment]
Should we make it optional and leave the default value in DetectorParams, if KGain cal file not available. Or should we delete the kgain value in DetectorParams?

**Comment by kjl0025** [comment]
Sorry I didn't get back to you sooner on this!  I shared my thoughts on your PR.

**Comment by semaphoreP** [comment]
Added in PR #211
