### ISSUE TITLE
Lots of NaNs in flat field computation for Uranus

### ISSUE THREAD

**Issue by ajeldorado** [roman-corgi/corgidrp#221]
**Describe the bug**
When running test_create_flatfield.py, FITS files are produced for flat fields computing using simulated data from Neptune and Uranus. The Neptune data is all values near 1.0, but a big chunk of the Uranus values (18743 pixels in total) on the bottom and left are NaNs (white in the figure below).
![case01_flat_field_neptune](https://github.com/user-attachments/assets/02a68b5d-5972-436d-a793-64bccbef9beb)
![case01_flat_field_uranus](https://github.com/user-attachments/assets/40aeee9d-8236-4bf0-be2d-8e274e38db23)

**To Reproduce**
Run `pytest tests/test_create_flatfield.py` and look at the output sim_flatfield_uranus_4.fits.

**Expected behavior**
I expected either for the flat field to have no NaN values, only a few scattered pixels with NaN values, or an explanation in the test script comments saying that there should be a ton of NaN values.

**corgidrp version:**
Main branch on October 21, 2024: commit dd521bdfdbca2168e37b9034db6f1b82ba374eb4

**Additional context**
It is unclear whether the observed behavior with lots of NaNs in the Uranus flat field is intended or not.

**Comment by semaphoreP** [comment]
Thanks for catching that! I will look into it. Regardless, looks like our unit tests should be checking for NaNs.
