### ISSUE TITLE
Write unit tests for sorting EM-gain, k-gain and non-linearity calibration data

### ISSUE THREAD

**Issue by hsergi** [roman-corgi/corgidrp#232]
This is a feature that comes as one of the to-do tasks of this parent issue about EM-gain, k-gain and non-linearity: https://github.com/roman-corgi/corgidrp/issues/226

The task is:

Write unit tests that cover the file diversity that mat happen when collecting calibration data for EM-gain, k-gain and non-linearity

**Comment by semaphoreP** [comment]
Finished in PR #247
