### ISSUE TITLE
Compute apparent magnitude of source in CGI band

### ISSUE THREAD

**Issue by semaphoreP** [roman-corgi/corgidrp#237]
**Is your feature request related to a problem? Please describe.**
Given the magnitude of the star in a standard filter band and the star's spectra type, compute the apparent magnitude of the source in the CGI band and store it in the header

**Describe the solution you'd like**
The above in a step function. 

**Additional context**
Need to figure out where the CGI filter profiles are, but they should already be documented

**Comment by JuergenSchreiber** [comment]
I guess you mean something like a color correction factor?

**Comment by semaphoreP** [comment]
Yep, exactly it.

**Comment by semaphoreP** [comment]
@JuergenSchreiber, I was just looking over this issue more closely, and I'm not sure #259 fully solves this issue, because we computed a color correction, but we didn't go all the way and compute the apparent magnitude in the CGI band. Is that correct?

**Comment by JuergenSchreiber** [comment]
Well, we will compute the flux in the CGI bands, and I think we could convert the units to magnitudes. But that might not be trivial since we do not have the standard UBV filters. Since the goal is the calibration of the ND filter, so relative fluxes is good enough, I think the final unit is not that important as long as we stay at the same all the time. Is this reasonable?

**Comment by semaphoreP** [comment]
I think we want vega magnitudes, so given a filter profile and a vega spectrum, it should be doable.

I only emphasized magnitudes, because that's what's listed in the design document. I think for the science data, we do want to be able to calculate the apparent magnitude of both the star and any point sources around it (not just the flux ratio). So we do need some way to convert to fluxes (not just relative fluxes to the star).

**Comment by JuergenSchreiber** [comment]
Ok, so please keep this issue open, I will write it in a header keyword
