### ISSUE TITLE
DQ fields should be integer types not float types

### ISSUE THREAD

**Issue by ecady-jpl** [roman-corgi/corgidrp#267]
**Is your feature request related to a problem? Please describe.**
The definition for the contents of the DQ matrix (section 4.0 of the Corgi-DRP Implementation Document) clearly show it as implemented as a series of bit flags that can be masked to identify bad pixels in general or ones flagged for meeting a certain criterion in particular.  This is fine.  What doesn't make sense is that DQ is implemented in practice with a 64-bit float.  A floating-type should never be used for bit masking as the bit flag positions will change based on the total value of the number.

**Describe the solution you'd like**
Change DQ to an integer type, preferably unsigned (signed has no use case here).

**Comment by semaphoreP** [comment]
I'm pretty sure it's an integer right now. Perhaps the documentation is wrong.

**Comment by semaphoreP** [comment]
I just spot-checked a couple of files I made with the DRP, and they both are int DQ extensions. I would ask for an example or a bug-reproduction script to see when this is not true.

**Comment by ecady-jpl** [comment]
Looks like the documentation is wrong then.  I'll discuss with @mygouf about who needs to do the cleanup on the SSC wiki.  But we can close this up here.

**Comment by maxwellmb** [comment]
@ecady-jpl I'll note that we still think they're 64-bit integers. if I'm understanding the origin of this concern correctly (data volume), you might still want it on your radar.

**Comment by ecady-jpl** [comment]
@maxwellmb I am wary of data volume, and do think you ought to scrub it.  But this one is just a straight mismatch--you can't bitmask floats because the bits will float around depending on what bits are set...

**Comment by maxwellmb** [comment]
Ok good good. I agree it'd be a problem if it were float. Vanessa also mentioned the data volume thing the other day and the idea of forcing the bit depth for a future release has come up.

**Comment by agreenbaum** [comment]
I would also advocate for reducing data volume in cases like this. Happy to join the discussion if/when it comes up.

**Comment by kjl0025** [comment]
I just corrected the data format page (https://collaboration.ipac.caltech.edu/display/romancoronagraph/Data+Array+Formats) to say that the DQ is 64-bit integer (as it is currently in the DRP).
