### ISSUE TITLE
Update and expand contributing guide

### ISSUE THREAD

**Issue by dsavransky** [roman-corgi/corgidrp#29]
Contributing guide in README (potentially should move to its own page) could use a few more details on individual steps, and currently does not include information on forking.

**Comment by maxwellmb** [comment]
I don't doubt that this is true. @dsavransky would you mind providing some more specific suggestions that motivated this comment?

**Comment by dsavransky** [comment]
Primarily based on my earlier question about accepting pulls from people not explicitly added to the repo - this requires that they fork first, so we should describe that in the contributor guide.  I'm happy to provide text.

**Comment by maxwellmb** [comment]
@dsavransky pinging you on this. Cleaning up old issues.

**Comment by maxwellmb** [comment]
Thanks @dsavransky!
