### ISSUE TITLE
 Port L1 -> L2a JPL II&T code Part 2: Cosmic Ray rejection

### ISSUE THREAD

**Issue by maxwellmb** [roman-corgi/corgidrp#33]
This is an off-shoot of issue #12, L1_to_L2a.

I'm breaking it up since we want this part to be a separate function

This will implement the following steps:
- Build per-frame cosmic ray masks and remove cosmic rays

**Comment by JuergenSchreiber** [comment]
connected to #24

**Comment by maxwellmb** [comment]
The FDD requires that we output a per-frame cosmic ray mask. We should do this as a new fits extension HDU.

**Comment by semaphoreP** [comment]
Can we check that the DQ frame we are already saving sufficiently satisfies this criterion?

**Comment by maxwellmb** [comment]
I think @nasavbailey and I decided later in the same conversation that it does.

**Comment by maxwellmb** [comment]
> connected to #24, I would propose to keep the dq values after interpolation of bad pixels to keep knowing where problems could occur

I think we have a DQ value to indicate that a pixel was replaced (and we'd keep the original DQ value too).

**Comment by maxwellmb** [comment]
Closing this with PR #120, #121 and #86
