### ISSUE TITLE
Develop astrometric calibration functions

### ISSUE THREAD

**Issue by semaphoreP** [roman-corgi/corgidrp#4]
Develop code to measure the platescale, north angle, and distortion solution from a dataset or multiple datasets. 

Requires
- simulating LMC calibration fields
- find and measure position of sources
- compare positions against reference
- measure boresight (reference pix) of CGI
- measure average platescale and north angle
- measure distortion solution (ask Jason if you need code)
- determine where platescale/north angle values will be stored. determine where distortion solution will be stored

**Comment by semaphoreP** [comment]
boresight calibration is top priority

**Comment by maxwellmb** [comment]
A lot of work of this has been done already by @hsergi and others. Don't start without talking to him

**Comment by maxwellmb** [comment]
A good place to start is also looking at @rzellem's paper: https://ui.adsabs.harvard.edu/abs/2022SPIE12180E..1ZZ/abstract

**Comment by hsergi** [comment]
Thanks @maxwellmb. I will double check which material needs unlimited release and which can just be shared. Targeting next Tue 02/16. Feel free to ping me.

**Comment by semaphoreP** [comment]
for the boresight calibration, this will be done before the optical alignment is done. We need to talk with Eric Cady regarding how ratty the PSF will be and develop the code to be robust to this. 

Note that the full astrometric calibration post-boresight calibration will be done one a much better PSF. This is the reason the initial boresight calibration sequence is separate from the full astrometric calibration.

**Comment by semaphoreP** [comment]
I'm closing this issue now that PR #113 is done, and will make a new issue for fine-precision astrometric solution + disotriton map.
