### ISSUE TITLE
Update Image Class to track each individual error term

### ISSUE THREAD

**Issue by semaphoreP** [roman-corgi/corgidrp#41]
Turn the Error extension into a 3-D datacube, where each slice is the contribution from one souce of noise (e.g., dark subtraction). The final slice should be all of the terms combined in quadrature. The header of the error extension should record which term is filling which index of the 3-D cube. We may need to make sure the error extension header is appropriately being tracked throughout processing. 

There should also be a function in `Image` called something like `add_error_term()` to add additional error terms.

**Comment by semaphoreP** [comment]
Based on discussion in #25

**Comment by maxwellmb** [comment]
In the end maybe it should always be the fist slice. Then new error slices
just get slapped onto the end. Seems simpler and may where one would expect
to look?

**Comment by semaphoreP** [comment]
Sounds good. First slice is the sum of all errors.

**Comment by JuergenSchreiber** [comment]
I take it since I already started on these items

**Comment by semaphoreP** [comment]
Implemented in PR #45. Thanks!
