### ISSUE TITLE
Compute EMGAIN when applicable

### ISSUE THREAD

**Issue by semaphoreP** [roman-corgi/corgidrp#46]
Before non-linearity correction, we need a step that populates an EMGAIN keyword in the header. 

As per @maxwellmb 

  1. If the commanded emgain is 1 we probably don't need to do anything. I'm looking in to the header keyword we might expect. There's one that is CMDGAIN that is the commanded gain, but I don't know if that's the K-gain or the emgain at the moment (I've asked Alex).
  2. If the EM Gain is v high we can measure it from the pre-scan region.
  3. If the EM gain is lower then we may not be able to do that, and I believe that it's an outstanding task to figure out how to do this.

I suggest we have a step function that we call no matter what. If CMDGAIN =1 (assuming this is the correct keyword) then it just sets EMGAIN=1, otherwise it does a calculation and sets the keyword. In all cases its that same function that is responsible for setting that keyword. Calculating EMGAIN is a required step that doesn't have a stub yet, only because I based the stubs off the ttr5_analog.py script which wasn't based on the EMGAIN workflow. It should be done.

**Comment by maxwellmb** [comment]
From the Zellem calibration paper:
For high gains (i.e., G > 1000) the calibration can be done using the raw images themselves, as they contain a prescan region, where serial clock induced charge (CIC) undergoes the same gain process as real image region signal. A histogram of the counts in the prescan region shows predominantly read-noise-only readings, but also includes, at roughly the 2% level, EM-gain multiplied CIC events. Frames where the gain is set to < 1000 will need to be calibrated using a special artificial flat
field generated using a custom clocking sequence, very similar to what is done for trap pumping.

This probably requires separate functions for each case.

**Comment by kjl0025** [comment]
There exists a function that finds the actual EM gain that was applied for a frame on the Calibration repo, whether high or low.  @nasavbailey , are we privy to that for corgidrp?  That module (EM_gain_fit) is currently not in the cal folder of cgi_iit_drp.

**Comment by nasavbailey** [comment]
@kjl0025 : I saw that the header of EMGain_cal.py said "This module calibrates the EM gain with the commanded DAC value." I saw "DAC" and thought it might include FSW or flight hardware details (ie: export-controlled info), so I didn't export it. Let's discuss the content of that function offline and port over if it's not flight software?

**Comment by kjl0025** [comment]
Yes, that script EMGain_cal.py does involve DAC-to-gain conversion, but the files in the EM_gain_fit folder do not invoke DAC at all.  It just does a statistical fit to the frame data.  Sure, we can talk more offline.

**Comment by maxwellmb** [comment]
Closing this issue to have it superseded by Issue #49
