### ISSUE TITLE
Port L2a -> L2b JPL II&T code: Desmears frame if desmear_flag is set to True

### ISSUE THREAD

**Issue by mygouf** [roman-corgi/corgidrp#51]

**Comment by maxwellmb** [comment]
I think with the current recipe architecture that we're discussing (to be finalized) we won't need a flag, but instead this step will be included (or not) in a recipe.

**Comment by maxwellmb** [comment]
Sets a DESMEAR header keyword to True or False.

**Comment by maxwellmb** [comment]
Closing this with PR #89
