### ISSUE TITLE
Port L2a -> L2b JPL II&T code: Divide by flat field

### ISSUE THREAD

**Issue by mygouf** [roman-corgi/corgidrp#52]

**Comment by maxwellmb** [comment]
Erin Maier has written a nice paper on flat-fielding with CGI: https://arxiv.org/pdf/2202.04815.pdf

There is some code [here](https://github.com/roman-corgi/cgi_flat_fielding_tests). Let us know if you don't have access.

We want to port over the the code to a drp function to calculate a master flat field given input images.

**Comment by maxwellmb** [comment]
Anticipated completion: 2nd week of April.

**Comment by maxwellmb** [comment]
Closing this with PR #88
