### ISSUE TITLE
mocks.py function create_default_headers() throws warning

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#54]
Change header "DATA_LEVEL" to a hierarch card so that warning isn't given (since the string is >8 characters).

**Comment by semaphoreP** [comment]
Pretty easy fix. See snippet from astropy doc: https://docs.astropy.org/en/stable/io/fits/usage/headers.html

> If a keyword contains more than eight characters astropy will automatically use a HIERARCH card, but will also issue a warning in case this is in error. However, you may explicitly request a HIERARCH card by prepending the keyword with ‘HIERARCH ‘ (just as it would appear in the header). For example, hdr['HIERARCH abcdefghi'] will create the keyword abcdefghi without displaying a warning. Once created, HIERARCH keywords can be accessed like any other: hdr['abcdefghi'], without prepending ‘HIERARCH’ to the keyword.
