### ISSUE TITLE
mocks.py create_dark_calib_files() simulates data that causes occasional test failure

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#55]
Because fresh random data is generated each time `test_nonlinearity_correction.py` is tested, occasionally, the test in that file fails.  Instead of simulating the data each time, save some simulated data to a folder that we know passes and draw from that folder for the test in `test_nonlinearity_correction.py`.

**Comment by semaphoreP** [comment]
we should just use a fixed random seed. that avoids saving large binary data unnecessarily.
