### ISSUE TITLE
Port over:  calibration of synthesized master dark

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#65]

**Comment by kjl0025** [comment]
Also, a function in the dark class that will generate the synthetic dark given an input exposure time and EM gain (which assumes the calibration of the synthesized dark has been done).

**Comment by maxwellmb** [comment]
@kjl0025 , based on @JuergenSchreiber's comment in issue #50, should this issue include both the function that generates the calibration file and the function to generate a specific synthetic dark (included in the Dark class)?

**Comment by maxwellmb** [comment]
@kjl0025 is this closed with PR #105 ?

**Comment by kjl0025** [comment]
Yes!

**Comment by maxwellmb** [comment]
Amazing, thanks!

Closed with PR #105.
