### ISSUE TITLE
Make flatfielding package

### ISSUE THREAD

**Issue by rzellem** [roman-corgi/corgidrp#70]
Roman Coronagraph will use images of Uranus/Neptune as astrophysical flat sources. The planet will be dithered and imaged across the relevant field on EXCAM and the average astrophysical signal will be calculated via a matched filter. This common-mode planet image will then be divided out from each dither, leaving behind (ideally) a measurement of the gain map.

To further flatten the planet signal (as they can have surface features), CGI's fast steering mirror (FSM) will conduct a raster pattern to smooth out the planet's surface, hopefully making it easier to construct a matched filter.

For more details, please read:
https://ui.adsabs.harvard.edu/abs/2022arXiv220204815M/abstract

Erin Maier has some simulations, including some code that centroids on the planet's location, constructs a matched filter, and then estimates the flatfield here:
https://github.com/roman-corgi/cgi_flat_fielding_tests/blob/master/wfirst_flatfield_testing_all.ipynb

The code needs to be restructured to match the `corgidrp` formatting. @rzellem also has some code he has written to support FFT and TVAC testing.

**Comment by maxwellmb** [comment]
Closed with PR #151
