### ISSUE TITLE
when using the Image.copy() function for sub-classes of Image (e.g. Darks) the sub-class type is not copied

### ISSUE THREAD

**Issue by maxwellmb** [roman-corgi/corgidrp#81]
This was brought to my attention by the fact that @JuergenSchreiber created a new copy function for the KGain class in PR #80. 
You can see this like this: 
`import corgidrp.mocks as mocks
import corgidrp.detector as detector

dark_dataset = mocks.create_dark_calib_files()
dark_frame = detector.create_dark_calib(dark_dataset)
dark_frame_copy = dark_frame.copy()
print(type(dark_frame))
print(type(dark_frame_copy))`

Gives the output: 
<img width="215" alt="image" src="https://github.com/roman-corgi/corgidrp/assets/18196772/0c7f278e-3ea9-47ae-b9e9-01f73f560093">

Hopefully there's a way we can generalize this without the need for new copy methods for each new calibration datatype.

**Comment by semaphoreP** [comment]
unfortunately the best solution is to write a new version of the copy() class, unless we can guarantee that all constructors have the same signature (all `__init__()` functions take the same constructor). There is a hack we can do, but I can't guarantee it'll always work

**Comment by semaphoreP** [comment]
Only if that function actually gets used.

**Comment by maxwellmb** [comment]
I suppose. It's low priority, but I still think something we want eventually.

**Comment by maxwellmb** [comment]
I made a new low priority tag

**Comment by JuergenSchreiber** [comment]
If we want to use the copy module, we could save writing copy functions.
I tested it on a kgain instance and it seems to work:
import copy
#reference copy
kgain_copy = copy.copy(kgain)
#deep data copy
kgain_copy = copy.deepcopy(kgain)

What do you think?

**Comment by semaphoreP** [comment]
Good idea!

**Comment by semaphoreP** [comment]
Sounds good!

**Comment by maxwellmb** [comment]
Closed with Merge PR #217

**Comment by maxwellmb** [comment]
So that I understand, @JuergenSchreiber, your PR #217, updated the readme, but it doesn't affect existing implementations, right?

**Comment by JuergenSchreiber** [comment]
@maxwellmb yes, correct

**Comment by maxwellmb** [comment]
Should we just replace the innards of the existing `copy` functions to use `copy.deepcopy()` instead?

**Comment by semaphoreP** [comment]
sounds like a good idea to me

**Comment by JuergenSchreiber** [comment]
I am not sure whether I understand what you mean. Deleting the existing copy functions? The copy module also works with the existing copy functions. I think the drawback is that it does not update the drp version and time header keywords 
'DRPVERSN" and "DRPCTIME", which the existing copy functions do.

**Comment by semaphoreP** [comment]
I think Max might mean take the ~10 other lines of code that involve new object creation and use deepcopy(), but still keep the few extra lines of code that moidfy DRPVERSN and DRPCTIME

**Comment by JuergenSchreiber** [comment]
I have created a new branch  copy_replace where I removed the copy functions from the subclasses and used the Image.copy function using the copy module. It seems to work. Could you please check whether we should make a PR out of it?

**Comment by semaphoreP** [comment]
Took a glance at it, and it looks good to me. we can iterate details in PR if needed

**Comment by semaphoreP** [comment]
Addressed in #248
