### ISSUE TITLE
cosmic ray masking update

### ISSUE THREAD

**Issue by kjl0025** [roman-corgi/corgidrp#91]
The masking of cosmic rays using the GSW tool for this was not sufficient to create good noise maps (arrays of dark current, CIC, and FPN per pixel in the image area).  It has since been updated and delivered and does lead to good-quality noise maps.  Need to update the cosmic-ray masking function accordingly.

**Comment by maxwellmb** [comment]
This is related to Issue #72, so I'm going to close this one and leave that one open.

**Comment by mygouf** [comment]
@kjl0025 I see you are still assigned to this issue, are you planning to work on this still or would you need help with this?

**Comment by kjl0025** [comment]
Ah yes, I did instinctively assign myself. :) However, I was thinking that once you (or someone) pulls in the latest cosmic ray code on corgi_iit_drp, perhaps Ell could implement the changes since she did the initial port of the cosmic code?  I could do it, but I am running low on funding for this work.
